### PR TITLE
Task 7

### PR DESCRIPTION
**Pull request by safonovaA**
Valid athorization_token: Basic c2Fmb25vdmFhOlRFU1RfUEFTU1dPUkQ ( localStorage.setItem('authorization_token', 'Basic c2Fmb25vdmFhOlRFU1RfUEFTU1dPUkQ') )
Link to FE: https://d2zahg5j3ns57l.cloudfront.net/
Link to FE PR: https://github.com/safonovaA/nodejs-aws-fe/pull/6
Main part: 
- 1 - authorization-service is added to the repo, has correct basicAuthorizer lambda and correct serverless.yaml file
- 3 - import-service serverless.yaml file has authorizer configuration for the importProductsFile lambda. Request to the importProductsFile lambda should work only with correct authorization_token being decoded and checked by basicAuthorizer lambda. Response should be in 403 HTTP status if access is denied for this user (invalid authorization_token) and in 401 HTTP status if Authorization header is not provided.
- 5 - update client application to send Authorization: Basic authorization_token header on import. 

Additional:
- +1 - Client application should display alerts for the responses in 401 and 403 HTTP statuses

### CODE REVIEW

**Comment by MaxGaranin** [comment]
When I tried to open https://d2zahg5j3ns57l.cloudfront.net/admin/products I get 403 error, strange.
Please provide in PR link to import-service.

**Comment by candentira** [comment]
Got 401 alert when no authorization_token was set to localStorage
image

However got 500 error when set correct authorization_token
image

**Comment by safonovaA** [comment]
@candentira Actually, I can't reproduce the described issue:  
image

**Comment by candentira** [comment]
@safonovaA You're expecting `authorization_token` to be set in format "**Basic** base64-encoded({github_account}:TEST_PASSWORD)" which is a bit unexpected. With this format I'm getting 403 error.
(As you can note on screenshots above I was setting localStorage value like this: `localStorage.setItem('authorization_token', 'base64-encoded({github_account}:TEST_PASSWORD)')`)

However I still couldn't get 200.
Could you please provide correct auth_token as `base64(safonovaA:TEST_PASSWORD)` is `c2Fmb25vdmFBOlRFU1RfUEFTU1dPUkQ=` which is not the one that you've used on your first screenshot and with auth_token `Basic c2Fmb25vdmFBOlRFU1RfUEFTU1dPUkQ=` I'm still getting 403 error.

**Comment by safonovaA** [comment]
> @safonovaA You're expecting `authorization_token` to be set in format "**Basic** base64-encoded({github_account}:TEST_PASSWORD)" which is a bit unexpected. With this format I'm getting 403 error.
> (As you can note on screenshots above I was setting localStorage value like this: `localStorage.setItem('authorization_token', 'base64-encoded({github_account}:TEST_PASSWORD)')`)
> 
> However I still couldn't get 200.
> Could you please provide correct auth_token as `base64(safonovaA:TEST_PASSWORD)` is `c2Fmb25vdmFBOlRFU1RfUEFTU1dPUkQ=` which is not the one that you've used on your first screenshot and with auth_token `Basic c2Fmb25vdmFBOlRFU1RfUEFTU1dPUkQ=` I'm still getting 403 error.

@candentira The valid token is provided in description. Token `Basic c2Fmb25vdmFhOlRFU1RfUEFTU1dPUkQ` or in console `localStorage.setItem('authorization_token', 'Basic c2Fmb25vdmFhOlRFU1RfUEFTU1dPUkQ')`

**Comment by candentira** [comment]
@safonovaA Got 200. Thank you.

**Pull request merged**
